site_name: "dist-gis-exercises (Distributed GIS & Cloud Computing - Exercises)"
repo_url: "https://github.com/muratkendir/dist-gis-exercises/"
site_url: "https://muratkendir.github.io/dist-gis-exercises/"
#edit_uri: "tree/main/docs"
exclude_docs: |
  /html_documents/
  /notebooks/
nav:
  - Home: index.md
  - "Exercise 1" :
    - "Distributed Systems" : distributed_systems.md
    - "Docker Usage (Bonus)" : docker_usage.md
  - "Exercise 2" :
    - "Introduction to Python" : intro_python.md
    - "Spatial Data Infrastructures" : sdis.md
    - "Networks & Internet (Bonus)" : networks_internet.md
  - "Exercise 4 (Web Map)": exercise4.md
  - "Exercise 5 (Virtualization)": 
    - "Preparation for Exercise 5": exercise5_preparation.md
    - "Exercise 5": exercise5.md
  - "OGC Service Samples": samples_for_discussion.md
  - "Essentials of Web Mapping": essentials_of_web_mapping.md
  - "Virtual Env. Installation":
    - "Windows w PIP": install_w_pip_on_win.md
    - "Linux w PIP": install_w_pip_on_lnx.md
  - "Sample OGC Services": ogc_services_samples.md
theme: material
extra_css:
  - extra_style.css
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
